### ISSUE TITLE
Quick Action error when creating a new task

### ISSUE THREAD

**Issue by atomicangel** [go-vikunja/vikunja#1048]
### Description

When attempting to create a new task using the Quick Action menu, I receive a "No_project" error in the lower left corner. 

I do not have any projects besides the default Inbox, if that matters. When I tested this on the demo page, it had a project already created and even after deletion of the project created a task from the Quick Action worked as expected. I then made a project on my instance and the issue still remained, so something to do with the self-hosted variant seems to be the case.

### Vikunja Version

Version: v0.24.6

### Browser and version

Firefox 139, Fedora Kinoite 42

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
This should go away if you set the inbox project as the default project in the user settings. Does that work for you?

There have been a few issues around this, all of which should be fixed but not yet released (that's why it works on the demo)

**Comment by atomicangel** [comment]
I had Inbox set as my default project from the beginning but just to be on the safe side I double checked and confirmed. Verified the behavior is still occurring.

**Comment by kolaente** [comment]
Can you verify if this works with an unstable build?

**Comment by atomicangel** [comment]
I apologize, I haven't had the time to check into this. I am running the docker version, and when I change my docker compose to vikunja/unstable or vikunja/latest I am getting access denied or repo does not exist.

**Comment by kolaente** [comment]
The docker image has a tag of unstable, it's not a separate image. The full image would be `vikunja/vikunja:unstable`.

**Comment by atomicangel** [comment]
Confirmed that unstable is working as expected.
