### ISSUE TITLE
Todoist Import Fails

### ISSUE THREAD

**Issue by eXpl0it3r** [go-vikunja/vikunja#1788]
### Description

I just tried Vikunja, installed the self-hosted variant via Docker, and followed the instruction for the [Todoist import](https://vikunja.io/docs/setup-todoist-migration/).

After starting the import, I waited for a while and nothing appeared. Peaking into the logs, I noticed that the import has failed at one point:

```
[Migration] Migration 1 from todoist for user 1 failed. Error was: json: cannot unmarshal object into Go value of type []*todoist.project
```

I enabled DEBUG level logging, recreated the container and restarted the import, which succeeded, but all I got were a bunch of loose tasks. No projects, no assignments.

```
[Migration] Successfully done migration 2 from todoist for user 1
```

I deleted the data and tried again and both times it failed with an EOF error.

```
[Migration] Migration 1 from todoist for user 1 failed. Error was: EOF
...
[Migration] Migration 2 from todoist for user 1 failed. Error was: EOF
```

Unfortunately, the debug logs don't really provide more information, before the failure, they simple contain lines like these:

```
...
time=2025-11-12T12:59:55.947Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8691841602"
time=2025-11-12T12:59:56.392Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8692407142"
time=2025-11-12T12:59:56.851Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8685111639"
time=2025-11-12T12:59:57.169Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8685109059"
time=2025-11-12T12:59:57.621Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8688092617"
time=2025-11-12T12:59:58.623Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8688092719"
time=2025-11-12T12:59:58.886Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8688092927"
time=2025-11-12T12:59:59.092Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8688094275"
time=2025-11-12T12:59:59.341Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8688094755"
time=2025-11-12T12:59:59.582Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8668602738"
time=2025-11-12T12:59:59.960Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8668604721"
time=2025-11-12T13:00:00.871Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8668606872"
time=2025-11-12T13:00:05.440Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8668607719"
time=2025-11-12T13:00:08.918Z level=DEBUG msg="[Todoist Migration] Retrieved full task data for done task 8678150681"
```

### Vikunja Version

v1.0.0-rc2

### Browser and version

LibreWolf

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

<img width="794" height="291" alt="Image" src="https://github.com/user-attachments/assets/1ac5f006-7829-4a2b-a440-c6dd7094471e" />

**Comment by kolaente** [comment]
It seems like on some occasions, the Todoist API would return a status 503 and Vikunja did not handle this properly. I've implemented retries in https://github.com/go-vikunja/vikunja/commit/9efc0baf503061c305eb0d81e8f68426a0d5f063 and proper errors in these cases in https://github.com/go-vikunja/vikunja/commit/8862b6f69d35cc4dcc64221a1308ce9e2e2d000f. In my own tests, everything works fine now, please check with the next unstable build.

**Comment by eXpl0it3r** [comment]
Oh that was quick, thanks a lot!

The migration seems to have succeeded, but I still don't see any projects.

Does the importer even import that projects from Todoist?

**Comment by kolaente** [comment]
Do the projects show up if you reload?

**Comment by eXpl0it3r** [comment]
Ohh, they do! 🎉 

Thank you! 🙂 

I guess this means, the migration was fully successful!
