### ISSUE TITLE
Date Localization Issues with dayjs

### ISSUE THREAD

**Issue by davide-ruota** [go-vikunja/vikunja#391]
### Description

Hi, I have some issues with date localization. I initially thought it was due to localization settings, but I realized it depends on the localization provided by dayjs.

I also checked on https://try.vikunja.io and noticed that other languages besides Italian have localization issues.
In practice, only German, French, and Russian are translated correctly, and maybe a few others (I haven't checked everything). 

### Vikunja Version

v0.24.1-657-8ba9ded3e2

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![mXcBhDF](https://github.com/user-attachments/assets/f9e5f0a9-5445-4c06-90cc-197feecb9191)

**Comment by kolaente** [comment]
This seems to be a problem with our loading of these translations. The [italian translation files seem correct](https://github.com/iamkun/dayjs/blob/dev/src/locale/it.js). @dpschen Do you have an idea what could be wrong here?

**Comment by dpschen** [comment]
I would assume that the dayjs language mapping is the issue here, since it doesn't seem like it's in sync.

<img width="933" alt="Screenshot 2025-01-14 at 10 53 38" src="https://github.com/user-attachments/assets/86f654d0-d995-404c-bec0-d3c7ef76c61f" />

**Comment by kolaente** [comment]
Crowdin syncs all languages, but only those with translated strings of more than 50% are added to `SUPPORTED_LOCALES`. That's why not all languages we have files for are included.

Italian is included correctly, but the date strings are not used?

**Comment by dpschen** [comment]
I see, will check further, thanks for clarification!

I wasn't aware that Crowdin also changed the `SUPPORTED_LOCALES` list. Maybe we should add a comment there. Or to make it even more obvious we could generate the list in an external file that gets imported in `i18n/index.ts`.

Why do we add json files of languages that have less than 50%?

**Comment by kolaente** [comment]
> I wasn't aware that Crowdin also changed the SUPPORTED_LOCALES list

It doesn't, the crowdin sync will only create the files. Adding a language to `SUPPORTED_LOCALES` is a manual process.

> Why do we add json files of languages that have less than 50%?

That's a limitation of the crowdin sync job.

**Comment by kolaente** [comment]
It looks like the part of Vikunja from the screenshot in the first comment does not use dayjs, but date-fns (a different library) 🙃 

https://github.com/go-vikunja/vikunja/blob/main/frontend/src/helpers/time/formatDate.ts#L4-L5

Why again do we have _two_ date libraries?

**Comment by kolaente** [comment]
PR is up: https://kolaente.dev/vikunja/vikunja/pulls/3039

**Comment by kolaente** [comment]
> And besides I have other inserts from English, although everything is translated in Crowdin.

Not all translated strings are approved. Only approved strings will show up in Vikunja.

**Comment by kolaente** [comment]
Fixed in 021d71b90e, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

**Comment by jon4god** [comment]
From what I understand the changes can be viewed at https://try.vikunja.io/. Checked it out. There's still a problem with the dates.
Gone are the remnants of English from the settings.

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/bd00139d-50ab-4593-96e4-eafbda6f0ec7" />
<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/f7023f9c-1503-4038-ab54-9437ccbcf128" />

**Comment by kolaente** [comment]
This seems to affect a handful of languages, but it's completely unclear to me why. Dayjs has all the required translations.

**Comment by jon4god** [comment]
I'm not good at js, but I read that if you use dayjs on a multilingual site, you should use i18n:localeSwitched. 
It allows you to switch dayjs localization when you switch site locale.

Is this used?

**Comment by kolaente** [comment]
> you should use i18n:localeSwitched

This seems to be a Nuxt thing, which we don't use. Might be a problem with `dayjs.locale`. I'll check.

**Comment by kolaente** [comment]
It seems like this was caused by an incorrect setting, a few layers deep:

1. When formatting dates, we explicitly set the locale during the call to dayjs.
2. Because Vikunja uses region-aware locale codes and dayjs doesn't, we need a translation between the two.
3. This happened differently in different parts of the codebase. In some places we've used a mapping object which we've maintained by hand. In the formatting function, we've used a translation string `date.locale`. This works great in theory, but for Russian and a few other languages that string was "translated" to `en`. That meant the language for dates was explicitly set to `en` when these languages were selected.

I've fixed this now in 4e979f3375a3bb276ca0b5569b932065fda0c4f0 - please check with the next unstable build, you know how it works.
